#!/bin/bash
#
#Notes you should have a look at before running this script. Thanks Roger ;-)
#
#1. In order to run a script you must have the line above entered as the first
#   line in the exact format
#
#2. You will need to give permission to your system in order to run this
#   program, at command line "chmod +x ruby-pi"
#
#3. If the script is in your current directory, but the current directory “.” is not in your search path, you’ll need to pre- pend “./” so the shell finds the script:
$ ./ruby-pi

echo "My name is Hal, starting to Ruby on Rails load process"
echo "Thanks for using my script - Roger Swanson, Charleston, SC USA, http://rogerswanson.me" 
#echo "My name is $1 and I come from $2"

#Ruby-PI setup for RaspberryPI running Debian
#Scripts written by Roger Swanson (@roger_swanson), Charleston, SC
#OpenLicense Message goes here! :-)
#
sudo apt-get install -y git curl zlib1g-dev subversion
sudo apt-get update
sudo apt-get install -y openssl libreadline6-dev git-core zlib1g libssl-dev
sudo apt-get install -y libyaml-dev libsqlite3-dev sqlite3
sudo apt-get install -y libxml2-dev libxslt-dev
sudo apt-get install -y autoconf automake libtool bison
curl -L get.rvm.io | bash -s stable --rails
#be sure to look for this line so you can source your rails files
#* To start using RVM you need to run `source /home/pi/.rvm/scripts/rvm`
#   in all your open shell windows, in rare cases you need to reopen all shell windows.
#
# * To start using rails you need to run `rails new <project_dir>`.
ruby -v
rails -v
#these are the dependancies that need to be loaded
gem install execjs
sudo apt-get install nodejs

#These are the commands to run a simple RubyOnRails Test
#I have created another script "ror-test-school"
#remember to run this script you must make it executable 
#chmod +x ror-test-school
#to run script "./ror-test-school"
#go into a new directory enter command "mkdir projects"
#build it yourself or clone the simple project I made up on git hub
#rails new school
#cd school
#rails g scaffold Pupil name:string teacher:string class:string
#rake db:migrate
#rails server



