#!/bin/bash
echo "My name is Hal"
#echo "My name is $1 and I come from $2"

#Ruby-PI setup for RaspberryPI running Debian
#Scripts written by Roger Swanson (@roger_swanson), Charleston, SC
#OpenLicense
#You will need to give permission to your system in order to run this
#program, at command line "chmod +x ruby-pi"

