#!/bin/bash
#
#Notes you should have a look at before running this script. Thanks Roger ;-)
#
#1. In order to run a script you must have the line above entered as the first
#   line in the exact format
#
#2. You will need to give permission to your system in order to run this
#   program, at command line "chmod +x ruby-pi"
#
#3. If the script is in your current directory, but the current directory “.” is not in your search path, you’ll need to pre- pend “./” so the shell finds the script:
#$ ./ruby-pi

echo "My name is Hal" 
pause
echo "My name is still Hal" 
#echo "My name is $1 and I come from $2"
echo "Would you like to continue? Please enter 'yes' to go on with the test script" read answer
case "$answer" in
yes)
echo "OK, here we go" ;;
*)
echo "I'm not sure what you want to do" echo "I guess I'll see you tomorrow"
;;
esac