#!/bin/bash
#
#Notes you should have a look at before running this script. Thanks Roger ;-)
#
#1. In order to run a script you must have the line above entered as the first
#   line in the exact format
#
#2. You will need to give permission to your system in order to run this
#   program, at command line "chmod +x ruby-pi"
#
#3. If the script is in your current directory, but the current directory “.” is not in your search path, you’ll need to pre- pend “./” so the shell finds the script:
#$ ./ruby-pi

echo "My name is Hal" 
#echo "My name is still Hal" 
#echo "My name is $1 and I come from $2"

echo "What would you like to do? (options: 'quit, or any other key to continue' " 
	read answer
case "$answer" in
quit)
echo "Good night then" 
break
;;
*)
echo "I'm not sure what you want to do" echo "I guess you can try again tomorrow"
;;
esac